name: uz_ai_dev
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.5+25

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get_it: ^8.2.0
  http: ^1.5.0
  image_picker: ^1.2.0
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  talker_dio_logger: ^5.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/assets/image.png"
